import html
import re
import datetime
import json
import os
from pathlib import Path

SITE_DIR = Path("site")
DOCS_DIR = Path("docs")
CONF_DIR = Path("conf")
SRC_DIR = Path("src/museum_yama_data")

PWA_THEME_COLOR = "#1f5f3b"
PWA_BACKGROUND_COLOR = "#f7faf7"

PWA_MANIFEST = {
    "name": "Yama Museum",
    "short_name": "Yama Museum",
    "description": "Documentation and data lineage overview for mountaineering GPX and YAMAP activity data.",
    "id": "./",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "background_color": PWA_BACKGROUND_COLOR,
    "theme_color": PWA_THEME_COLOR,
    "prefer_related_applications": False,
    "icons": [
        {
            "src": "assets/icons/yama-museum-192.svg",
            "type": "image/svg+xml",
            "sizes": "192x192",
            "purpose": "any maskable",
        },
        {
            "src": "assets/icons/yama-museum-512.svg",
            "type": "image/svg+xml",
            "sizes": "512x512",
            "purpose": "any maskable",
        },
    ],
}

ICON_SVG_TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="0 0 512 512" role="img" aria-labelledby="title desc">
  <title id="title">Yama Museum icon</title>
  <desc id="desc">A stylized mountain ridge with a route line and summit marker.</desc>
  <rect width="512" height="512" rx="96" fill="#1f5f3b"/>
  <circle cx="390" cy="122" r="42" fill="#f6d365"/>
  <path d="M64 372L196 152l84 140 56-88 112 168H64z" fill="#f7faf7"/>
  <path d="M196 152l84 140 34-53 31 48c-62 18-121 18-173 0l24-135z" fill="#cfe8d8"/>
  <path d="M108 386c52-72 112-72 164-28 46 38 92 38 132-16" fill="none" stroke="#f6d365" stroke-width="28" stroke-linecap="round"/>
  <circle cx="403" cy="342" r="25" fill="#f6d365" stroke="#1f5f3b" stroke-width="12"/>
</svg>
"""

def write_pwa_assets():
    icons_dir = SITE_DIR / "assets" / "icons"
    icons_dir.mkdir(parents=True, exist_ok=True)

    with open(SITE_DIR / "manifest.webmanifest", "w") as f:
        json.dump(PWA_MANIFEST, f, indent=2)
        f.write("\n")

    for size in (192, 512):
        with open(icons_dir / f"yama-museum-{size}.svg", "w") as f:
            f.write(ICON_SVG_TEMPLATE.format(size=size))


def get_template(title, content):
    nav = """
    <nav>
        <a href="index.html">Home</a>
        <a href="data-catalog.html">Data Catalog</a>
        <a href="pipeline.html">Pipeline</a>
        <a href="pipeline-graph.html">Pipeline Graph</a>
        <a href="directory-inventory.html">Directory Inventory</a>
        <a href="lineage.html">Lineage</a>
        <a href="decisions.html">Decisions</a>
    </nav>
    """
    timestamp = os.environ.get("SOURCE_DATE_EPOCH")
    date_str = ""
    if timestamp:
        try:
            date_str = " on " + datetime.datetime.fromtimestamp(int(timestamp), datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        except ValueError:
            pass

    footer = f"""
    <footer>
        <p>Generated by scripts/build_site.py as a summary of canonical project policies{date_str}.</p>
    </footer>
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Yama Museum</title>
    <meta name="theme-color" content="{PWA_THEME_COLOR}">
    <link rel="manifest" href="manifest.webmanifest">
    <link rel="icon" href="assets/icons/yama-museum-192.svg" type="image/svg+xml" sizes="any">
    <link rel="stylesheet" href="assets/site.css">
</head>
<body>
    {nav}
    <main>
        <h1>{title}</h1>
        {content}
    </main>
    {footer}
</body>
</html>"""


GRAPH_NODES = [
    # Col 1: Sources
    {"id": "raw_gpx_activities", "label": "raw_gpx_activities", "type": "node-source", "col": 0, "row": 0},
    {"id": "raw_yamap_activity_metadata", "label": "raw_yamap_activity_metadata", "type": "node-source", "col": 0, "row": 3},
    {"id": "raw_reverse_geocoding_cache", "label": "raw_reverse_geocoding_cache", "type": "node-source", "col": 0, "row": 1},
    {"id": "raw_activity_workbook", "label": "raw_activity_workbook", "type": "node-source", "col": 0, "row": 4},
    {"id": "curated_mountain_research_docs", "label": "curated_mountain_research_docs", "type": "node-source", "col": 0, "row": 5},

    # Col 2: Early Processes
    {"id": "parse_gpx", "label": "parse_gpx()", "type": "node-process", "col": 1, "row": 0},

    # Col 3: Intermediate Datasets
    {"id": "gpx_tracks", "label": "gpx_tracks", "type": "node-derived", "col": 2, "row": 0},
    {"id": "gpx_trackpoints", "label": "gpx_trackpoints", "type": "node-derived", "col": 2, "row": 1},

    # Col 4: Mid Processes
    {"id": "detect_summit_candidates", "label": "detect_summit_candidates()", "type": "node-process", "col": 3, "row": 0},
    {"id": "estimate_municipality", "label": "estimate_municipality()", "type": "node-process", "col": 3, "row": 1},

    # Col 5: Mid Derived
    {"id": "summit_candidates", "label": "summit_candidates", "type": "node-derived", "col": 4, "row": 0},
    {"id": "location_enrichment", "label": "location_enrichment", "type": "node-derived", "col": 4, "row": 1},

    # Col 6: Identity Enrichment Processes
    {"id": "collect_identity_evidence", "label": "collect_identity_evidence()", "type": "node-process", "col": 5, "row": 1},

    # Col 7: Evidence Dataset
    {"id": "mountain_identity_evidence", "label": "mountain_identity_evidence", "type": "node-derived", "col": 6, "row": 1},

    # Col 8: Resolve Process
    {"id": "resolve_mountain_identity", "label": "resolve_mountain_identity()", "type": "node-process", "col": 7, "row": 0},
    {"id": "build_activity_mountain_links", "label": "build_activity_mountain_links()", "type": "node-process", "col": 7, "row": 2},

    # Col 9: Resolved Outputs
    {"id": "mountains", "label": "mountains", "type": "node-derived", "col": 8, "row": 0},
    {"id": "summit_identity_candidates", "label": "summit_identity_candidates", "type": "node-derived", "col": 8, "row": 1},
    {"id": "activity_mountain_links", "label": "activity_mountain_links", "type": "node-derived", "col": 8, "row": 2},

    # Col 10: Export / Reporting Processes
    {"id": "export_summit_candidate_gpx", "label": "export_summit_candidate_gpx()", "type": "node-process", "col": 9, "row": 0},
    {"id": "export_resolved_mountain_waypoints", "label": "export_resolved_mountain_waypoints()", "type": "node-process", "col": 9, "row": 1},
    {"id": "export_web_data", "label": "export_web_data()", "type": "node-process", "col": 9, "row": 2},
    {"id": "validate_outputs", "label": "validate_outputs()", "type": "node-process", "col": 9, "row": 3},

    # Col 11: Final Outputs
    {"id": "summit_candidate_gpx", "label": "summit_candidate_gpx", "type": "node-reporting", "col": 10, "row": 0},
    {"id": "resolved_mountain_waypoint_gpx", "label": "resolved_mountain_waypoint_gpx", "type": "node-reporting", "col": 10, "row": 1},
    {"id": "web_data_exports", "label": "web_data_exports", "type": "node-reporting", "col": 10, "row": 2},
    {"id": "validation_reports", "label": "validation_reports", "type": "node-reporting", "col": 10, "row": 3},
]

GRAPH_EDGES = [
    # parse_gpx
    ("raw_gpx_activities", "parse_gpx"),
    ("parse_gpx", "gpx_tracks"),
    ("parse_gpx", "gpx_trackpoints"),

    # detect_summit_candidates
    ("gpx_tracks", "detect_summit_candidates"),
    ("gpx_trackpoints", "detect_summit_candidates"),
    ("detect_summit_candidates", "summit_candidates"),

    # export_summit_candidate_gpx
    ("summit_candidates", "export_summit_candidate_gpx"),
    ("export_summit_candidate_gpx", "summit_candidate_gpx"),

    # estimate_municipality
    ("summit_candidates", "estimate_municipality"),
    ("raw_reverse_geocoding_cache", "estimate_municipality"),
    ("estimate_municipality", "location_enrichment"),

    # collect_identity_evidence
    ("location_enrichment", "collect_identity_evidence"),
    ("raw_activity_workbook", "collect_identity_evidence"),
    ("raw_yamap_activity_metadata", "collect_identity_evidence"),
    ("curated_mountain_research_docs", "collect_identity_evidence"),
    ("collect_identity_evidence", "mountain_identity_evidence"),

    # resolve_mountain_identity
    ("summit_candidates", "resolve_mountain_identity"),
    ("mountain_identity_evidence", "resolve_mountain_identity"),
    ("resolve_mountain_identity", "summit_identity_candidates"),
    ("resolve_mountain_identity", "mountains"),

    # export_resolved_mountain_waypoints
    ("mountains", "export_resolved_mountain_waypoints"),
    ("mountain_identity_evidence", "export_resolved_mountain_waypoints"),
    ("export_resolved_mountain_waypoints", "resolved_mountain_waypoint_gpx"),

    # build_activity_mountain_links
    ("raw_yamap_activity_metadata", "build_activity_mountain_links"),
    ("mountains", "build_activity_mountain_links"),
    ("gpx_tracks", "build_activity_mountain_links"),
    ("build_activity_mountain_links", "activity_mountain_links"),

    # export_web_data
    ("resolved_mountain_waypoint_gpx", "export_web_data"),
    ("activity_mountain_links", "export_web_data"),
    ("export_web_data", "web_data_exports"),

    # validate_outputs (just general connection from pipeline outputs)
    ("resolved_mountain_waypoint_gpx", "validate_outputs"),
    ("activity_mountain_links", "validate_outputs"),
    ("summit_candidate_gpx", "validate_outputs"),
    ("validate_outputs", "validation_reports"),
]

def generate_svg_graph():
    node_w = 230
    node_h = 40
    col_spacing = 290
    row_spacing = 60
    margin_x = 20
    margin_y = 20

    max_col = max(n['col'] for n in GRAPH_NODES)
    max_row = max(n['row'] for n in GRAPH_NODES)

    svg_w = (max_col + 1) * col_spacing + margin_x * 2 - (col_spacing - node_w)
    svg_h = (max_row + 1) * row_spacing + margin_y * 2 - (row_spacing - node_h)

    # Pre-compute positions
    positions = {}
    for n in GRAPH_NODES:
        x = margin_x + n['col'] * col_spacing
        y = margin_y + n['row'] * row_spacing
        positions[n['id']] = (x, y)

    svg = []
    svg.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{svg_w}" height="{svg_h}" class="pipeline-graph" role="img" aria-labelledby="pipeline-graph-title pipeline-graph-desc">')
    svg.append('  <title id="pipeline-graph-title">Pipeline Graph</title>')
    svg.append('  <desc id="pipeline-graph-desc">A visual representation of the intended data processing pipeline</desc>')
    svg.append('<defs>')
    svg.append('  <marker id="arrow" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">')
    svg.append('    <path d="M 0 0 L 10 5 L 0 10 z" fill="#888" />')
    svg.append('  </marker>')
    svg.append('</defs>')

    # Draw edges
    for frm, to in GRAPH_EDGES:
        x1, y1 = positions[frm]
        x2, y2 = positions[to]

        # Center right of source
        start_x = x1 + node_w
        start_y = y1 + node_h / 2

        # Center left of target
        end_x = x2
        end_y = y2 + node_h / 2

        # A simple cubic bezier curve for edges
        cp1_x = start_x + (end_x - start_x) * 0.4
        cp1_y = start_y
        cp2_x = end_x - (end_x - start_x) * 0.4
        cp2_y = end_y

        svg.append(f'  <path d="M {start_x} {start_y} C {cp1_x} {cp1_y}, {cp2_x} {cp2_y}, {end_x} {end_y}" class="edge" fill="none" stroke="#888" stroke-width="2" marker-end="url(#arrow)" />')

    # Draw nodes
    for n in GRAPH_NODES:
        x, y = positions[n['id']]
        rect_class = n['type']
        label = n['label']

        svg.append(f'  <g class="node {rect_class}" transform="translate({x}, {y})">')
        svg.append(f'    <rect width="{node_w}" height="{node_h}" rx="4" ry="4" />')
        # Center text
        svg.append(f'    <text x="{node_w/2}" y="{node_h/2 + 5}" text-anchor="middle" font-family="sans-serif" font-size="12">{label}</text>')
        svg.append('  </g>')

    svg.append('</svg>')
    return "\n".join(svg)

def build_pipeline_graph():
    svg_content = generate_svg_graph()

    content = f"""
    <p>This graph represents the <strong>intended future pipeline structure</strong>.</p>
    <ul>
        <li>The pipeline stages are placeholders or planned stages unless otherwise documented.</li>
        <li>The graph is a presentation view derived from canonical repository sources.</li>
        <li>It does not imply that raw/source data has been moved out of Git.</li>
        <li><strong>Clone-complete / Git-primary / DVC-light remains the governing reproducibility policy.</strong></li>
    </ul>

    <div class="graph-container">
        {svg_content}
    </div>
    """

    with open(SITE_DIR / "pipeline-graph.html", "w") as f:
        f.write(get_template("Pipeline Graph", content))


def build_index():
    content = """
    <p>Welcome to the Yama Museum documentation site. This repository visualizes and analyzes mountaineering location data (GPX) and activity logs from the YAMAP app.</p>

    <h2>Project Policies</h2>
    <ul>
        <li><strong>Clone-Complete:</strong> A fresh Git clone contains primary data and retained processed artifacts needed for normal use.</li>
        <li><strong>No Git LFS:</strong> Git LFS is intentionally not used.</li>
        <li><strong>DVC-Light:</strong> DVC is used for pipeline metadata and reproducibility checks, not for removing primary data from Git by default.</li>
        <li><strong>Presentation Layer:</strong> This site is generated from canonical repository sources and does not expose raw/private/full data contents.</li>
    </ul>

    <h2>Quick Links</h2>
    <ul>
        <li><a href="data-catalog.html">Data Catalog</a></li>
        <li><a href="pipeline.html">Pipeline Architecture</a></li>
        <li><a href="pipeline-graph.html">Pipeline Graph</a></li>
        <li><a href="directory-inventory.html">Directory Inventory</a></li>
        <li><a href="lineage.html">Provenance & Lineage</a></li>
        <li><a href="decisions.html">Decisions & Status</a></li>
    </ul>
    """
    with open(SITE_DIR / "index.html", "w") as f:
        f.write(get_template("Yama Museum Overview", content))

def clean_value(val):
    # Remove markdown backticks and html escape
    val = val.replace("`", "").strip()
    return html.escape(val)

def extract_field(line, prefix):
    # Extracts the text after the bold prefix, robust to formatting
    # E.g. "* **Prefix:** value" -> "value"
    parts = line.split(prefix, 1)
    if len(parts) > 1:
        return parts[1].strip()
    return ""

def build_data_catalog():
    # Simple extraction from target_data_model.md
    content = "<p>Conceptual datasets defined in the target data model.</p>\n"
    content += "<table><tr><th>Dataset</th><th>Layer</th><th>Status/Tracking</th></tr>\n"

    try:
        with open(DOCS_DIR / "migration" / "target_data_model.md", "r") as f:
            lines = f.readlines()
            current_dataset = ""
            layer = ""
            tracking = ""
            for line in lines:
                m = re.match(r"### \d+\.\s+`(.*?)`", line)
                if m:
                    if current_dataset:
                        content += f"<tr><td>{html.escape(current_dataset)}</td><td>{clean_value(layer)}</td><td>{tracking}</td></tr>\n"
                    current_dataset = m.group(1)
                    layer = ""
                    tracking = ""
                elif "* **Expected Future Layer:**" in line:
                    layer = extract_field(line, "* **Expected Future Layer:**")
                elif "* **Tracking System:**" in line:
                    tracking = clean_value(extract_field(line, "* **Tracking System:**"))
                elif "* **Status Notes:**" in line:
                    val = clean_value(extract_field(line, "* **Status Notes:**"))
                    tracking += f"<br><small>{val}</small>"
                elif "* **Note:**" in line:
                    val = clean_value(extract_field(line, "* **Note:**"))
                    tracking += f"<br><small>{val}</small>"

            if current_dataset:
                content += f"<tr><td>{html.escape(current_dataset)}</td><td>{clean_value(layer)}</td><td>{tracking}</td></tr>\n"
    except Exception as e:
        print(f"Error parsing data model: {e}")
        content += "<tr><td colspan='3'>Error parsing data model. See build logs for details.</td></tr>\n"

    content += "</table>\n"
    with open(SITE_DIR / "data-catalog.html", "w") as f:
        f.write(get_template("Data Catalog", content))

def build_pipeline():
    content = "<p>Intended future Kedro pipelines for data processing.</p>\n"
    content += "<table><tr><th>Pipeline</th><th>Inputs</th><th>Outputs</th><th>Status</th></tr>\n"

    try:
        with open(SRC_DIR / "pipelines" / "README.md", "r") as f:
            lines = f.readlines()
            current_pipe = ""
            inputs = ""
            outputs = ""
            status = ""
            for line in lines:
                m = re.match(r"### `(.*?)`", line)
                if m:
                    if current_pipe:
                        content += f"<tr><td>{html.escape(current_pipe)}</td><td>{clean_value(inputs)}</td><td>{clean_value(outputs)}</td><td>{clean_value(status)}</td></tr>\n"
                    current_pipe = m.group(1)
                    inputs = ""
                    outputs = ""
                    status = ""
                elif "* **Intended Inputs:**" in line:
                    inputs = extract_field(line, "* **Intended Inputs:**")
                elif "* **Intended Outputs:**" in line:
                    outputs = extract_field(line, "* **Intended Outputs:**")
                elif "* **Implementation Status:**" in line:
                    status = extract_field(line, "* **Implementation Status:**")

            if current_pipe:
                content += f"<tr><td>{html.escape(current_pipe)}</td><td>{clean_value(inputs)}</td><td>{clean_value(outputs)}</td><td>{clean_value(status)}</td></tr>\n"
    except Exception as e:
        print(f"Error parsing pipeline docs: {e}")
        content += "<tr><td colspan='4'>Error parsing pipeline docs. See build logs for details.</td></tr>\n"

    content += "</table>\n"
    with open(SITE_DIR / "pipeline.html", "w") as f:
        f.write(get_template("Pipeline Structure", content))

def build_lineage():
    content = """
    <p>This project models dataset-level and pipeline-stage-level lineage to trace data origins and transformations.</p>

    <h3>Graph Model</h3>
    <ul>
        <li><strong>Data/entity nodes:</strong> Datasets, files, or specific entities.</li>
        <li><strong>Process/activity nodes:</strong> Pipeline stages, scripts, or manual actions.</li>
        <li><strong>Evidence/method nodes:</strong> Supporting information, policies, or logic.</li>
    </ul>

    <h3>Edge Types</h3>
    <p>Relationships include: <code>used_by</code>, <code>generated_by</code>, <code>derived_from</code>, <code>supported_by</code>, <code>disambiguated_by</code>, <code>exported_from</code>, <code>validated_by</code>.</p>

    <h3>Future Graph Exports</h3>
    <p>Future pipeline stages will generate explicit graph representations in formats such as GraphML, Graphology JSON, and DOT.</p>

    <div style="background:#f4f4f4; padding:10px; border-radius:5px; margin-top:20px; font-family:monospace; white-space:pre;">
# Conceptual Lineage (DOT)
digraph Lineage {
    rankdir=LR;
    node [shape=box];

    raw_gpx [label="raw_gpx_activities"];
    parse [label="parse_gpx()", shape=ellipse];
    gpx_tracks [label="gpx_tracks"];

    raw_gpx -> parse [label="used_by"];
    parse -> gpx_tracks [label="generated_by"];
}
    </div>
    """
    with open(SITE_DIR / "lineage.html", "w") as f:
        f.write(get_template("Lineage & Provenance", content))

def build_decisions():
    content = """
    <p>Summary of key project decisions and current status.</p>

    <h3>Core Policies</h3>
    <ul>
        <li><strong>Clone-Complete:</strong> Primary data and retained artifacts remain in Git.</li>
        <li><strong>DVC-Light:</strong> DVC is used for metadata/dependencies, not for hiding raw data.</li>
        <li><strong>No Git LFS:</strong> LFS is not used to ensure simple cloning.</li>
    </ul>

    <h3>Pending "Needs Decision" Items</h3>
    <p>Data movement is blocked until these items are fully audited and resolved:</p>
    <ul>
        <li><code>csv/</code>: Excel-derived legacy CSV extracts; migration blocked pending validation of historical extraction script/logic.</li>
        <li><code>museum-yama-web/mountains.json</code>: Provisional legacy cache. Must not be treated as the final semantic model. Will be superseded by structured feature datasets and waypoint exports.</li>
        <li><code>gpx/annotated/</code>: Legacy unvalidated artifacts. Preserve as historical evidence.</li>
        <li><code>gpx/merged-by-year/</code>: Legacy reporting artifacts. Must be validated.</li>
    </ul>

    <h3>Two-Track Roadmap</h3>
    <p>Future work is split into two distinct tracks:</p>
    <ul>
        <li><strong>Website Improvements:</strong> Low-risk, incremental enhancements to the presentation layer.</li>
        <li><strong>Directory-Structure Improvements:</strong> Higher-risk changes to the underlying repository structure. This track is currently blocked. No physical data movement may occur until comprehensive source coverage and source-to-target mapping audits are complete.</li>
    </ul>
    <p>For more details, refer to the canonical source: <code><a href="https://github.com/TakashiSasaki/museum-yama-data/blob/HEAD/docs/migration/website_and_directory_roadmap.md" target="_blank" rel="noopener noreferrer">docs/migration/website_and_directory_roadmap.md</a></code>.</p>

    <h3>Audits</h3>
    <p>A new <a href="https://github.com/TakashiSasaki/museum-yama-data/blob/HEAD/docs/migration/source_to_target_mapping_audit.md" target="_blank" rel="noopener noreferrer">source-to-target mapping audit template</a> has been added as a starting point. It is not a completed audit and does not authorize data movement.</p>
    """
    with open(SITE_DIR / "decisions.html", "w") as f:
        f.write(get_template("Decisions & Status", content))

def build_directory_inventory():
    content = """
    <p>This page summarizes the current directory inventory and migration-readiness status.</p>

    <p><strong>Note:</strong> Physical directory restructuring remains blocked. The source of truth for the inventory is the canonical document: <code><a href="https://github.com/TakashiSasaki/museum-yama-data/blob/HEAD/docs/migration/current_directory_inventory.md" target="_blank" rel="noopener noreferrer">docs/migration/current_directory_inventory.md</a></code>.</p>

    <h3>Protected Directories (No Movement Yet)</h3>
    <ul>
        <li><code>gpx/</code> (raw, annotated, merged-by-year)</li>
        <li><code>csv/</code></li>
        <li><code>processed/</code></li>
        <li><code>yamap/</code></li>
        <li><code>reverse_geocoding/</code></li>
        <li><code>museum-yama-web/</code></li>
    </ul>

    <h3>Clone-Complete Reproducibility</h3>
    <p>All source data snapshots and retained legacy artifacts must be preserved. The project remains Git-primary and DVC-light. No protected data is being normalized or regenerated during this inventory phase.</p>

    <h3>Migration Readiness Audit Blockers</h3>
    <p>Movement of these protected directories may only proceed after:</p>
    <ul>
        <li>Every source path has a target disposition.</li>
        <li>Every source field is classified.</li>
        <li>No "needs decision" item remains.</li>
        <li>No "unmigrated gap" remains.</li>
    </ul>

    <p>See the <a href="https://github.com/TakashiSasaki/museum-yama-data/blob/HEAD/docs/migration/source_to_target_mapping_audit.md" target="_blank" rel="noopener noreferrer">source-to-target mapping audit template</a> for ongoing planning. It is a starting point and does not authorize data movement.</p>
    """
    with open(SITE_DIR / "directory-inventory.html", "w") as f:
        f.write(get_template("Directory Inventory", content))


if __name__ == "__main__":
    print("Building site...")
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    write_pwa_assets()
    build_index()
    build_data_catalog()
    build_pipeline()
    build_pipeline_graph()
    build_directory_inventory()
    build_lineage()
    build_decisions()
    print("Done.")