import re
import datetime
from pathlib import Path

SITE_DIR = Path("site")
DOCS_DIR = Path("docs")
CONF_DIR = Path("conf")
SRC_DIR = Path("src/museum_yama_data")

def get_template(title, content):
    nav = """
    <nav>
        <a href="index.html">Home</a>
        <a href="data-catalog.html">Data Catalog</a>
        <a href="pipeline.html">Pipeline</a>
        <a href="lineage.html">Lineage</a>
        <a href="decisions.html">Decisions</a>
    </nav>
    """
    footer = f"""
    <footer>
        <p>Generated by scripts/build_site.py from canonical docs/configuration sources on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}.</p>
    </footer>
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Yama Museum</title>
    <link rel="stylesheet" href="assets/site.css">
</head>
<body>
    {nav}
    <main>
        <h1>{title}</h1>
        {content}
    </main>
    {footer}
</body>
</html>"""

def build_index():
    content = """
    <p>Welcome to the Yama Museum documentation site. This repository visualizes and analyzes mountaineering location data (GPX) and activity logs from the YAMAP app.</p>

    <h2>Project Policies</h2>
    <ul>
        <li><strong>Clone-Complete:</strong> A fresh Git clone contains primary data and retained processed artifacts needed for normal use.</li>
        <li><strong>No Git LFS:</strong> Git LFS is intentionally not used.</li>
        <li><strong>DVC-Light:</strong> DVC is used for pipeline metadata and reproducibility checks, not for removing primary data from Git by default.</li>
        <li><strong>Presentation Layer:</strong> This site is generated from canonical repository sources and does not expose raw/private/full data contents.</li>
    </ul>

    <h2>Quick Links</h2>
    <ul>
        <li><a href="data-catalog.html">Data Catalog</a></li>
        <li><a href="pipeline.html">Pipeline Architecture</a></li>
        <li><a href="lineage.html">Provenance & Lineage</a></li>
        <li><a href="decisions.html">Decisions & Status</a></li>
    </ul>
    """
    with open(SITE_DIR / "index.html", "w") as f:
        f.write(get_template("Yama Museum Overview", content))

def build_data_catalog():
    # Simple extraction from target_data_model.md
    content = "<p>Conceptual datasets defined in the target data model.</p>"
    content += "<table><tr><th>Dataset</th><th>Layer</th><th>Status/Tracking</th></tr>"

    try:
        with open(DOCS_DIR / "migration" / "target_data_model.md", "r") as f:
            lines = f.readlines()
            current_dataset = ""
            layer = ""
            tracking = ""
            for line in lines:
                m = re.match(r"### \d+\.\s+`(.*?)`", line)
                if m:
                    if current_dataset:
                        content += f"<tr><td>{current_dataset}</td><td>{layer}</td><td>{tracking}</td></tr>"
                    current_dataset = m.group(1)
                    layer = ""
                    tracking = ""
                elif line.startswith("* **Expected Future Layer:**"):
                    layer = line.split("**")[2].strip().strip("`")
                elif line.startswith("* **Tracking System:**"):
                    tracking = line.split("**")[2].strip()
                elif line.startswith("* **Status Notes:**") or line.startswith("* **Note:**"):
                    tracking += "<br><small>" + line.split("**")[2].strip() + "</small>"

            if current_dataset:
                content += f"<tr><td>{current_dataset}</td><td>{layer}</td><td>{tracking}</td></tr>"
    except Exception as e:
        content += f"<tr><td colspan='3'>Error parsing data model: {e}</td></tr>"

    content += "</table>"
    with open(SITE_DIR / "data-catalog.html", "w") as f:
        f.write(get_template("Data Catalog", content))

def build_pipeline():
    content = "<p>Intended future Kedro pipelines for data processing.</p>"
    content += "<table><tr><th>Pipeline</th><th>Inputs</th><th>Outputs</th><th>Status</th></tr>"

    try:
        with open(SRC_DIR / "pipelines" / "README.md", "r") as f:
            lines = f.readlines()
            current_pipe = ""
            inputs = ""
            outputs = ""
            status = ""
            for line in lines:
                m = re.match(r"### `(.*?)`", line)
                if m:
                    if current_pipe:
                        content += f"<tr><td>{current_pipe}</td><td>{inputs}</td><td>{outputs}</td><td>{status}</td></tr>"
                    current_pipe = m.group(1)
                    inputs = ""
                    outputs = ""
                    status = ""
                elif line.startswith("* **Intended Inputs:**"):
                    inputs = line.split("**")[2].strip()
                elif line.startswith("* **Intended Outputs:**"):
                    outputs = line.split("**")[2].strip()
                elif line.startswith("* **Implementation Status:**"):
                    status = line.split("**")[2].strip()

            if current_pipe:
                content += f"<tr><td>{current_pipe}</td><td>{inputs}</td><td>{outputs}</td><td>{status}</td></tr>"
    except Exception as e:
        content += f"<tr><td colspan='4'>Error parsing pipeline docs: {e}</td></tr>"

    content += "</table>"
    with open(SITE_DIR / "pipeline.html", "w") as f:
        f.write(get_template("Pipeline Structure", content))

def build_lineage():
    content = """
    <p>This project models dataset-level and pipeline-stage-level lineage to trace data origins and transformations.</p>

    <h3>Graph Model</h3>
    <ul>
        <li><strong>Data/entity nodes:</strong> Datasets, files, or specific entities.</li>
        <li><strong>Process/activity nodes:</strong> Pipeline stages, scripts, or manual actions.</li>
        <li><strong>Evidence/method nodes:</strong> Supporting information, policies, or logic.</li>
    </ul>

    <h3>Edge Types</h3>
    <p>Relationships include: <code>used_by</code>, <code>generated_by</code>, <code>derived_from</code>, <code>supported_by</code>, <code>disambiguated_by</code>, <code>exported_from</code>, <code>validated_by</code>.</p>

    <h3>Future Graph Exports</h3>
    <p>Future pipeline stages will generate explicit graph representations in formats such as GraphML, Graphology JSON, and DOT.</p>

    <div style="background:#f4f4f4; padding:10px; border-radius:5px; margin-top:20px; font-family:monospace; white-space:pre;">
# Conceptual Lineage (DOT)
digraph Lineage {
    rankdir=LR;
    node [shape=box];

    raw_gpx [label="raw_gpx_activities"];
    parse [label="parse_gpx()", shape=ellipse];
    gpx_tracks [label="gpx_tracks"];

    raw_gpx -> parse [label="used_by"];
    parse -> gpx_tracks [label="generated_by"];
}
    </div>
    """
    with open(SITE_DIR / "lineage.html", "w") as f:
        f.write(get_template("Lineage & Provenance", content))

def build_decisions():
    content = """
    <p>Summary of key project decisions and current status.</p>

    <h3>Core Policies</h3>
    <ul>
        <li><strong>Clone-Complete:</strong> Primary data and retained artifacts remain in Git.</li>
        <li><strong>DVC-Light:</strong> DVC is used for metadata/dependencies, not for hiding raw data.</li>
        <li><strong>No Git LFS:</strong> LFS is not used to ensure simple cloning.</li>
    </ul>

    <h3>Pending "Needs Decision" Items</h3>
    <p>Data movement is blocked until these items are fully audited and resolved:</p>
    <ul>
        <li><code>csv/</code>: Needs confirmation of manual edit status and missing extraction script.</li>
        <li><code>museum-yama-web/mountains.json</code>: Provisional legacy cache. Must not be treated as the final semantic model. Will be superseded by structured feature datasets and waypoint exports.</li>
        <li><code>gpx/annotated/</code>: Legacy unvalidated artifacts. Preserve as historical evidence.</li>
        <li><code>gpx/merged-by-year/</code>: Legacy reporting artifacts. Must be validated.</li>
    </ul>
    """
    with open(SITE_DIR / "decisions.html", "w") as f:
        f.write(get_template("Decisions & Status", content))

if __name__ == "__main__":
    print("Building site...")
    build_index()
    build_data_catalog()
    build_pipeline()
    build_lineage()
    build_decisions()
    print("Done.")
