import html
import re
import datetime
import json
from pathlib import Path

SITE_DIR = Path("site")
DOCS_DIR = Path("docs")
CONF_DIR = Path("conf")
SRC_DIR = Path("src/museum_yama_data")

PWA_THEME_COLOR = "#1f5f3b"
PWA_BACKGROUND_COLOR = "#f7faf7"

PWA_MANIFEST = {
    "name": "Yama Museum",
    "short_name": "Yama Museum",
    "description": "Documentation and data lineage overview for mountaineering GPX and YAMAP activity data.",
    "id": "./",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "background_color": PWA_BACKGROUND_COLOR,
    "theme_color": PWA_THEME_COLOR,
    "prefer_related_applications": False,
    "icons": [
        {
            "src": "assets/icons/yama-museum-192.svg",
            "type": "image/svg+xml",
            "sizes": "192x192",
            "purpose": "any maskable",
        },
        {
            "src": "assets/icons/yama-museum-512.svg",
            "type": "image/svg+xml",
            "sizes": "512x512",
            "purpose": "any maskable",
        },
    ],
}

ICON_SVG_TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="0 0 512 512" role="img" aria-labelledby="title desc">
  <title id="title">Yama Museum icon</title>
  <desc id="desc">A stylized mountain ridge with a route line and summit marker.</desc>
  <rect width="512" height="512" rx="96" fill="#1f5f3b"/>
  <circle cx="390" cy="122" r="42" fill="#f6d365"/>
  <path d="M64 372L196 152l84 140 56-88 112 168H64z" fill="#f7faf7"/>
  <path d="M196 152l84 140 34-53 31 48c-62 18-121 18-173 0l24-135z" fill="#cfe8d8"/>
  <path d="M108 386c52-72 112-72 164-28 46 38 92 38 132-16" fill="none" stroke="#f6d365" stroke-width="28" stroke-linecap="round"/>
  <circle cx="403" cy="342" r="25" fill="#f6d365" stroke="#1f5f3b" stroke-width="12"/>
</svg>
"""

def write_pwa_assets():
    icons_dir = SITE_DIR / "assets" / "icons"
    icons_dir.mkdir(parents=True, exist_ok=True)

    with open(SITE_DIR / "manifest.webmanifest", "w") as f:
        json.dump(PWA_MANIFEST, f, indent=2)
        f.write("\n")

    for size in (192, 512):
        with open(icons_dir / f"yama-museum-{size}.svg", "w") as f:
            f.write(ICON_SVG_TEMPLATE.format(size=size))


def get_template(title, content):
    nav = """
    <nav>
        <a href="index.html">Home</a>
        <a href="data-catalog.html">Data Catalog</a>
        <a href="pipeline.html">Pipeline</a>
        <a href="lineage.html">Lineage</a>
        <a href="decisions.html">Decisions</a>
    </nav>
    """
    footer = f"""
    <footer>
        <p>Generated by scripts/build_site.py as a summary of canonical project policies on {datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")}.</p>
    </footer>
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - Yama Museum</title>
    <meta name="theme-color" content="{PWA_THEME_COLOR}">
    <link rel="manifest" href="manifest.webmanifest">
    <link rel="icon" href="assets/icons/yama-museum-192.svg" type="image/svg+xml" sizes="any">
    <link rel="stylesheet" href="assets/site.css">
</head>
<body>
    {nav}
    <main>
        <h1>{title}</h1>
        {content}
    </main>
    {footer}
</body>
</html>"""

def build_index():
    content = """
    <p>Welcome to the Yama Museum documentation site. This repository visualizes and analyzes mountaineering location data (GPX) and activity logs from the YAMAP app.</p>

    <h2>Project Policies</h2>
    <ul>
        <li><strong>Clone-Complete:</strong> A fresh Git clone contains primary data and retained processed artifacts needed for normal use.</li>
        <li><strong>No Git LFS:</strong> Git LFS is intentionally not used.</li>
        <li><strong>DVC-Light:</strong> DVC is used for pipeline metadata and reproducibility checks, not for removing primary data from Git by default.</li>
        <li><strong>Presentation Layer:</strong> This site is generated from canonical repository sources and does not expose raw/private/full data contents.</li>
    </ul>

    <h2>Quick Links</h2>
    <ul>
        <li><a href="data-catalog.html">Data Catalog</a></li>
        <li><a href="pipeline.html">Pipeline Architecture</a></li>
        <li><a href="lineage.html">Provenance & Lineage</a></li>
        <li><a href="decisions.html">Decisions & Status</a></li>
    </ul>
    """
    with open(SITE_DIR / "index.html", "w") as f:
        f.write(get_template("Yama Museum Overview", content))

def clean_value(val):
    # Remove markdown backticks and html escape
    val = val.replace("`", "").strip()
    return html.escape(val)

def extract_field(line, prefix):
    # Extracts the text after the bold prefix, robust to formatting
    # E.g. "* **Prefix:** value" -> "value"
    parts = line.split(prefix, 1)
    if len(parts) > 1:
        return parts[1].strip()
    return ""

def build_data_catalog():
    # Simple extraction from target_data_model.md
    content = "<p>Conceptual datasets defined in the target data model.</p>\n"
    content += "<table><tr><th>Dataset</th><th>Layer</th><th>Status/Tracking</th></tr>\n"

    try:
        with open(DOCS_DIR / "migration" / "target_data_model.md", "r") as f:
            lines = f.readlines()
            current_dataset = ""
            layer = ""
            tracking = ""
            for line in lines:
                m = re.match(r"### \d+\.\s+`(.*?)`", line)
                if m:
                    if current_dataset:
                        content += f"<tr><td>{html.escape(current_dataset)}</td><td>{clean_value(layer)}</td><td>{tracking}</td></tr>\n"
                    current_dataset = m.group(1)
                    layer = ""
                    tracking = ""
                elif "* **Expected Future Layer:**" in line:
                    layer = extract_field(line, "* **Expected Future Layer:**")
                elif "* **Tracking System:**" in line:
                    tracking = clean_value(extract_field(line, "* **Tracking System:**"))
                elif "* **Status Notes:**" in line:
                    val = clean_value(extract_field(line, "* **Status Notes:**"))
                    tracking += f"<br><small>{val}</small>"
                elif "* **Note:**" in line:
                    val = clean_value(extract_field(line, "* **Note:**"))
                    tracking += f"<br><small>{val}</small>"

            if current_dataset:
                content += f"<tr><td>{html.escape(current_dataset)}</td><td>{clean_value(layer)}</td><td>{tracking}</td></tr>\n"
    except Exception as e:
        print(f"Error parsing data model: {e}")
        content += "<tr><td colspan='3'>Error parsing data model. See build logs for details.</td></tr>\n"

    content += "</table>\n"
    with open(SITE_DIR / "data-catalog.html", "w") as f:
        f.write(get_template("Data Catalog", content))

def build_pipeline():
    content = "<p>Intended future Kedro pipelines for data processing.</p>\n"
    content += "<table><tr><th>Pipeline</th><th>Inputs</th><th>Outputs</th><th>Status</th></tr>\n"

    try:
        with open(SRC_DIR / "pipelines" / "README.md", "r") as f:
            lines = f.readlines()
            current_pipe = ""
            inputs = ""
            outputs = ""
            status = ""
            for line in lines:
                m = re.match(r"### `(.*?)`", line)
                if m:
                    if current_pipe:
                        content += f"<tr><td>{html.escape(current_pipe)}</td><td>{clean_value(inputs)}</td><td>{clean_value(outputs)}</td><td>{clean_value(status)}</td></tr>\n"
                    current_pipe = m.group(1)
                    inputs = ""
                    outputs = ""
                    status = ""
                elif "* **Intended Inputs:**" in line:
                    inputs = extract_field(line, "* **Intended Inputs:**")
                elif "* **Intended Outputs:**" in line:
                    outputs = extract_field(line, "* **Intended Outputs:**")
                elif "* **Implementation Status:**" in line:
                    status = extract_field(line, "* **Implementation Status:**")

            if current_pipe:
                content += f"<tr><td>{html.escape(current_pipe)}</td><td>{clean_value(inputs)}</td><td>{clean_value(outputs)}</td><td>{clean_value(status)}</td></tr>\n"
    except Exception as e:
        print(f"Error parsing pipeline docs: {e}")
        content += "<tr><td colspan='4'>Error parsing pipeline docs. See build logs for details.</td></tr>\n"

    content += "</table>\n"
    with open(SITE_DIR / "pipeline.html", "w") as f:
        f.write(get_template("Pipeline Structure", content))

def build_lineage():
    content = """
    <p>This project models dataset-level and pipeline-stage-level lineage to trace data origins and transformations.</p>

    <h3>Graph Model</h3>
    <ul>
        <li><strong>Data/entity nodes:</strong> Datasets, files, or specific entities.</li>
        <li><strong>Process/activity nodes:</strong> Pipeline stages, scripts, or manual actions.</li>
        <li><strong>Evidence/method nodes:</strong> Supporting information, policies, or logic.</li>
    </ul>

    <h3>Edge Types</h3>
    <p>Relationships include: <code>used_by</code>, <code>generated_by</code>, <code>derived_from</code>, <code>supported_by</code>, <code>disambiguated_by</code>, <code>exported_from</code>, <code>validated_by</code>.</p>

    <h3>Future Graph Exports</h3>
    <p>Future pipeline stages will generate explicit graph representations in formats such as GraphML, Graphology JSON, and DOT.</p>

    <div style="background:#f4f4f4; padding:10px; border-radius:5px; margin-top:20px; font-family:monospace; white-space:pre;">
# Conceptual Lineage (DOT)
digraph Lineage {
    rankdir=LR;
    node [shape=box];

    raw_gpx [label="raw_gpx_activities"];
    parse [label="parse_gpx()", shape=ellipse];
    gpx_tracks [label="gpx_tracks"];

    raw_gpx -> parse [label="used_by"];
    parse -> gpx_tracks [label="generated_by"];
}
    </div>
    """
    with open(SITE_DIR / "lineage.html", "w") as f:
        f.write(get_template("Lineage & Provenance", content))

def build_decisions():
    content = """
    <p>Summary of key project decisions and current status.</p>

    <h3>Core Policies</h3>
    <ul>
        <li><strong>Clone-Complete:</strong> Primary data and retained artifacts remain in Git.</li>
        <li><strong>DVC-Light:</strong> DVC is used for metadata/dependencies, not for hiding raw data.</li>
        <li><strong>No Git LFS:</strong> LFS is not used to ensure simple cloning.</li>
    </ul>

    <h3>Pending "Needs Decision" Items</h3>
    <p>Data movement is blocked until these items are fully audited and resolved:</p>
    <ul>
        <li><code>csv/</code>: Needs confirmation of manual edit status and missing extraction script.</li>
        <li><code>museum-yama-web/mountains.json</code>: Provisional legacy cache. Must not be treated as the final semantic model. Will be superseded by structured feature datasets and waypoint exports.</li>
        <li><code>gpx/annotated/</code>: Legacy unvalidated artifacts. Preserve as historical evidence.</li>
        <li><code>gpx/merged-by-year/</code>: Legacy reporting artifacts. Must be validated.</li>
    </ul>

    <h3>Two-Track Roadmap</h3>
    <p>Future work is split into two distinct tracks:</p>
    <ul>
        <li><strong>Website Improvements:</strong> Low-risk, incremental enhancements to the presentation layer.</li>
        <li><strong>Directory-Structure Improvements:</strong> Higher-risk changes to the underlying repository structure. This track is currently blocked. No physical data movement may occur until comprehensive source coverage and source-to-target mapping audits are complete.</li>
    </ul>
    <p>For more details, refer to the canonical source: <code><a href="https://github.com/TakashiSasaki/museum-yama-data/blob/museum-yama-data/docs/migration/website_and_directory_roadmap.md" target="_blank">docs/migration/website_and_directory_roadmap.md</a></code>.</p>
    """
    with open(SITE_DIR / "decisions.html", "w") as f:
        f.write(get_template("Decisions & Status", content))

if __name__ == "__main__":
    print("Building site...")
    SITE_DIR.mkdir(parents=True, exist_ok=True)
    write_pwa_assets()
    build_index()
    build_data_catalog()
    build_pipeline()
    build_lineage()
    build_decisions()
    print("Done.")